version: '3.8'

services:
  todo-frontend:
    container_name: todo-frontend
    build: ./frontend
    ports:
      - 4000:80
    networks:
      - todo-app
    environment:
      - BACKEND_SERVER=${BACKEND_SERVER}
    depends_on:
      - todo-backend

  todo-backend:
    container_name: todo-backend
    build: ./backend
    ports:
      - 3001:3001
    networks:
      - todo-app
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
networks:
  todo-app:
